export const SELECT_PRODUCT = "SELECT_PRODUCT";

export const CLOSE_MODAL_ORDER = "CLOSE_MODAL_ORDER";

export const ADD_LIST_PRODUCT_ORDER = "ADD_LIST_PRODUCT_ORDER";

export const EDIT_LIST_PRODUCT_ORDER = "EDIT_LIST_PRODUCT_ORDER";
